"""Extract a drug library (per-layer steering vectors) following Sofroniew
et al.'s methodology: mean-difference at *each* extraction layer, applied
*at that layer* during inference.

For each drug we generate ~150 contrastive stories, run them through the
model with hooks at all target layers (default L16-24), and compute one
vector per (drug, layer). The library .pt then stores
`{drug_name: {layer_idx: vector_tensor}}`.

Story sources, in priority order:
  1. Built-in `ryancodrai/emotion-probes` for each emotion that exists there.
  2. `extra_stories.parquet` (generated by `generate_stories.py`) for the
     custom drugs (blissful / focused / persistent / etc.).
  3. Neutral baseline always comes from `ryancodrai/emotion-probes`.

Run after the vLLM server is up::

    uv run python -m hackday.drugs.extract \\
        --base-url http://localhost:8000 \\
        --layers 16 17 18 19 20 21 22 23 24 \\
        --stories-per-drug 150 \\
        --output src/hackday/drugs/library.pt
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import torch
from datasets import Dataset, load_dataset
from vllm_lens import Hook
from vllm_lens._examples.emotion_tracker import compute_emotion_vectors
from vllm_lens.client import VLLMLensClient

from hackday.drugs.library import DEFAULT_DRUGS, STEERING_LAYERS_BY_MODE

# Token offset to start mean-pooling from — early tokens haven't yet
# absorbed the story's content; matches Sofroniew et al.'s setup.
MIN_TOKEN_OFFSET = 50

# Default extraction layers — multi-mode covers L16-24 (mid-late layers
# where emotion concepts are stable, per Sofroniew Figure 9).
DEFAULT_LAYERS = list(range(16, 25))

# Default probe layer — the deepest extraction layer. Overridden at
# runtime to max(args.layers) so different models work without changes.
DEFAULT_PROBE_LAYER = 24

# Drugs sourced from the custom Sonnet-generated parquet rather than the
# emotion-probes HF dataset. (Anything in DEFAULT_DRUGS but not in the
# emotion-probes dataset.)
CUSTOM_DRUGS = {
    # Round 2
    "blissful", "focused", "persistent",
    # Round 3
    "calm", "melancholic", "creative", "dumbed_down",
    "honest", "sycophantic", "mdma", "lsd",
    "golden_gate", "goblins",
    # Round 4 (kept set — the abstract-mechanism drugs cut for v3)
    "protozosin", "geonexperine", "tevromatin",
    "xaomorphine", "zorninone", "luciperidone", "ocumolone",
    "moloko_plus", "adrenochrome", "krokodil", "fentanyl",
    "spice", "soma", "naloxone",
    # Round 5: regular / common drugs + missing emotion axes
    "curious", "dissociated", "amphetamine", "weed", "alcohol",
    "ego_death", "caffeine", "anhedonic",
}

EXTRA_STORIES_PATHS = [
    # Round-3 obsession v2 — supersedes the round-3 entries for
    # golden_gate and goblins, which used a prompt that didn't actually
    # name the obsession (so the vector encoded "fog/cables" instead of
    # "Golden Gate Bridge"). Listed first so v2 stories take priority.
    Path(__file__).parent / "extra_stories_round3_obsession_v2.parquet",
    Path(__file__).parent / "extra_stories.parquet",          # round 2
    Path(__file__).parent / "extra_stories_round3.parquet",   # round 3 (extended palette)
    Path(__file__).parent / "extra_stories_round4.parquet",   # round 4 (SSC + fictional)
    Path(__file__).parent / "extra_stories_round5.parquet",   # round 5 (regular drugs)
    Path(__file__).parent / "extra_stories_round5_topup.parquet",  # round 5 topup (curious/ego_death/caffeine)
]

# Drugs whose round-3 corpus should be ignored (superseded by v2). Loader
# drops any story for these drugs if it came from extra_stories_round3.parquet.
SUPERSEDED_IN_ROUND3 = {"golden_gate", "goblins"}


def load_stories_mixed(
    drugs: list[str], n_per_drug: int
) -> tuple[dict[str, list[str]], list[str]]:
    """Load stories for each drug from the right source, plus neutrals.

    Returns (drug_stories, neutral_stories).
    """
    print("Loading stories...")

    # Built-in HF emotion-probes for every drug not in CUSTOM_DRUGS.
    builtin_drugs = [d for d in drugs if d not in CUSTOM_DRUGS]
    custom_drugs = [d for d in drugs if d in CUSTOM_DRUGS]

    drug_stories: dict[str, list[str]] = {}

    if builtin_drugs:
        ds = load_dataset(
            "ryancodrai/emotion-probes",
            data_files="expression/stories.parquet",
        )["train"]
        for d in builtin_drugs:
            matches = [r["story"] for r in ds if r["emotion"] == d][:n_per_drug]
            if matches:
                drug_stories[d] = matches
                print(f"  {d}: {len(matches)} stories from emotion-probes")
            else:
                print(f"  WARNING: {d!r} not found in emotion-probes")

    if custom_drugs:
        # Pull stories from any of the round-N parquet files we have.
        # Track per-row source so we can drop superseded round-3 entries.
        all_extra_rows: list[tuple[str, dict[str, Any]]] = []
        sources_used: list[str] = []
        for p in EXTRA_STORIES_PATHS:
            if p.exists():
                ds = Dataset.from_parquet(str(p))
                for row in ds:
                    all_extra_rows.append((p.name, row))
                sources_used.append(p.name)
        if not all_extra_rows:
            raise FileNotFoundError(
                f"Custom drugs requested ({custom_drugs}) but no "
                f"extra_stories*.parquet found in "
                f"{EXTRA_STORIES_PATHS[0].parent}. Run "
                f"`uv run python -m hackday.drugs.generate_stories` first."
            )
        for d in custom_drugs:
            # Drop round-3 entries for drugs that v2 supersedes
            matches = [
                row["story"]
                for source, row in all_extra_rows
                if row["emotion"] == d
                and not (
                    d in SUPERSEDED_IN_ROUND3
                    and source == "extra_stories_round3.parquet"
                )
            ][:n_per_drug]
            if matches:
                drug_stories[d] = matches
                tag = " (v2 obsession-prompt)" if d in SUPERSEDED_IN_ROUND3 else ""
                print(
                    f"  {d}: {len(matches)} stories{tag}"
                )
            else:
                print(f"  WARNING: {d!r} not found in any extra_stories*.parquet")

    # Neutral stories always come from emotion-probes.
    neutral_ds = load_dataset(
        "ryancodrai/emotion-probes",
        data_files="expression/neutral_stories.parquet",
    )["train"]
    neutral_stories = [r["story"] for r in neutral_ds][:n_per_drug]
    print(f"  neutral: {len(neutral_stories)} stories")

    return drug_stories, neutral_stories


def extract_mean_activations_multilayer(
    client: VLLMLensClient,
    texts: list[str],
    layers: list[int],
    label: str = "",
) -> dict[int, torch.Tensor]:
    """Extract mean-pooled activations at every layer in `layers` in one
    pass. Returns dict mapping layer -> tensor of shape (n_texts, hidden_dim).

    One Hook is registered with `layer_indices=layers`; vllm-lens fires the
    capture function at each of those layers per text, and we collect
    per-layer tensors at the end.
    """
    def capture_mean_from_50(ctx, h):
        start = min(MIN_TOKEN_OFFSET, h.shape[0] - 1)
        ctx.saved[f"mean_L{ctx.layer_idx}"] = h[start:].mean(dim=0).cpu()
        return None

    hook = Hook(fn=capture_mean_from_50, layer_indices=layers)

    client.register_hooks([hook])
    for i, text in enumerate(texts):
        client.generate(text, max_tokens=1)
        if (i + 1) % 25 == 0:
            print(f"    {label} {i + 1}/{len(texts)}")

    results = client.collect_hook_results()
    client.clear_hooks()

    per_layer: dict[int, list[torch.Tensor]] = {L: [] for L in layers}
    for req_id in sorted(results.keys()):
        hook_data = results[req_id]["0"]
        for L in layers:
            per_layer[L].append(hook_data[f"mean_L{L}"])

    return {L: torch.stack(per_layer[L]) for L in layers}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-url", default="http://localhost:8000")
    parser.add_argument(
        "--drugs",
        nargs="+",
        default=list(DEFAULT_DRUGS.keys()),
        help="Drug names to extract.",
    )
    parser.add_argument(
        "--layers",
        nargs="+",
        type=int,
        default=DEFAULT_LAYERS,
        help="Layers to capture in one pass (default: L16-24).",
    )
    parser.add_argument(
        "--stories-per-drug",
        type=int,
        default=150,
        help="Per-drug story count.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/hackday/drugs/library.pt"),
    )
    parser.add_argument(
        "--multi-target-norm",
        type=float,
        default=None,
        help=(
            "Per-model calibrated steering norm for `multi` mode, stored in "
            "the library as target_norm_by_mode['multi'] so load_library "
            "rescales to it instead of the Qwen-tuned global default. "
            "Required for non-Qwen models with very different residual "
            "magnitudes (e.g. Gemma-3 ~900 vs Qwen ~4)."
        ),
    )
    args = parser.parse_args()

    probe_layer = max(args.layers)

    client = VLLMLensClient(args.base_url)
    print(f"Server model: {client.model}")
    print(f"Capture layers: {args.layers}  probe layer: {probe_layer}")
    print(f"Drugs: {args.drugs}")
    print(f"Stories per drug: {args.stories_per_drug}\n")

    drug_stories, neutral_stories = load_stories_mixed(
        args.drugs, args.stories_per_drug
    )

    print("\nExtracting drug activations (per-layer)...")
    # drug_acts_by_layer[layer][drug] = (n_texts, hidden_dim)
    drug_acts_by_layer: dict[int, dict[str, torch.Tensor]] = {
        L: {} for L in args.layers
    }
    for drug, stories in drug_stories.items():
        print(f"  {drug}:")
        per_layer = extract_mean_activations_multilayer(
            client, stories, args.layers, label=drug
        )
        for L in args.layers:
            drug_acts_by_layer[L][drug] = per_layer[L]

    print("  neutral:")
    neutral_per_layer = extract_mean_activations_multilayer(
        client, neutral_stories, args.layers, label="neutral"
    )

    print("\nComputing drug vectors per layer...")
    # vectors_by_drug_layer[drug][layer] = vector
    vectors_by_drug_layer: dict[str, dict[int, torch.Tensor]] = {
        d: {} for d in drug_stories
    }
    for L in args.layers:
        per_layer_drug_acts = drug_acts_by_layer[L]
        per_layer_neutral_acts = neutral_per_layer[L]
        layer_vectors = compute_emotion_vectors(
            per_layer_drug_acts, per_layer_neutral_acts
        )
        for drug, vec in layer_vectors.items():
            vectors_by_drug_layer[drug][L] = vec
        print(f"  L{L}: extracted {len(layer_vectors)} drug vectors")

    # Print norm summary for sanity check (first / middle / last extraction layer)
    L_lo, L_mid, L_hi = args.layers[0], args.layers[len(args.layers) // 2], args.layers[-1]
    print(f"\nNorm summary (L{L_lo}, L{L_mid}, L{L_hi}):")
    for drug in vectors_by_drug_layer:
        vs = vectors_by_drug_layer[drug]
        lo = vs[L_lo].norm() if L_lo in vs else float("nan")
        mid = vs[L_mid].norm() if L_mid in vs else float("nan")
        hi = vs[L_hi].norm() if L_hi in vs else float("nan")
        print(f"  {drug:<14} {lo:.2f} / {mid:.2f} / {hi:.2f}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    save_payload: dict[str, Any] = {
        # New v2 format: {drug_name: {layer_idx: vector}}
        "emotion_vectors": vectors_by_drug_layer,
        "descriptions": {
            d: DEFAULT_DRUGS[d] for d in vectors_by_drug_layer if d in DEFAULT_DRUGS
        },
        "extraction_layers": args.layers,
        "probe_layer": probe_layer,
        "model": client.model,
        "stories_per_drug": args.stories_per_drug,
        "library_format_version": 2,
        "available_modes": list(STEERING_LAYERS_BY_MODE),
    }
    if args.multi_target_norm is not None:
        save_payload["target_norm_by_mode"] = {"multi": args.multi_target_norm}
    torch.save(save_payload, args.output)
    print(f"\nSaved drug library to {args.output}")


if __name__ == "__main__":
    main()
